# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
variables:
  sp: 'splearnaks'
  rg_name: 'storacc-rg'
  location: 'West Europe'
pool:
  vmImage: ubuntu-latest
stages:
- stage:
  jobs:
    - job: tfstate
      steps:
      - task: AzurePowerShell@5
        displayName: Configure remote state storage account
        inputs:
          azureSubscription: 'SP Terraform'
          ScriptType: 'InlineScript'
          Inline: |
            # Create resource group
            if (-not (Get-AzResourceGroup -Name $(rg_name) -Location $(location) -ErrorAction SilentlyContinue)) {
              New-AzResourceGroup -Name $(rg_name) -Location $(location)
              # Create storage account
              $storageAccount = New-AzStorageAccount -ResourceGroupName $(rg_name) -Name $(storage_name) -SkuName $(k8s-sku) -Location $(location) -AllowBlobPublicAccess $false            
              # Create blob container
              New-AzStorageContainer -Name $(container_name) -Context $storageAccount.context
            }
          azurePowerShellVersion: 'LatestVersion'
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
