
trigger: none
variables:
  sp: 'splearnaks'
  rg_name: 'storacc-rg'
  location: 'WestEurope'
  storage_name: 'storaccxyz001'
  storagekey: ''
pool:
  vmImage: ubuntu-latest
stages:
- stage:
  jobs:
    - job: tfstate
      steps:
      - task: AzurePowerShell@5
        displayName: Configure remote state storage account
        inputs:
          azureSubscription: '$(sp)'
          ScriptType: 'InlineScript'
          azurePowerShellVersion: 'LatestVersion'
          Inline: |
            # Create resource group
            if (-not (Get-AzResourceGroup -Name $(rg_name) -Location $(location) -ErrorAction SilentlyContinue)) {
              New-AzResourceGroup -Name $(rg_name) -Location $(location)
              # Create storage account
              $storageAccount = New-AzStorageAccount -ResourceGroupName $(rg_name) -Name $(storage_name)  -Location $(location) -AllowBlobPublicAccess $false
              # Create blob container
              New-AzStorageContainer -Name $(container_name) -Context $storageAccount.context
            }
      - task: AzurePowerShell@5
        displayName: Configure terraform backend state
        inputs:
          azureSubscription: '$(sp)'
          ScriptType: 'InlineScript'
          azurePowerShellVersion: 'LatestVersion'
          Inline: |
            $ACCOUNT_KEY=(Get-AzStorageAccountKey -ResourceGroupName $(rg_name) -Name $(storage_name))[0].value
            Write-Host "##vso[task.setvariable variable=storagekey]$ACCOUNT_KEY"
            Write-Output 'storagekey' $storagekey
            Write-Output 'storagekey' $(storagekey)
