# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest
variables:
  dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
  tag: $(Build.BuildId)
steps:
- task: Docker@2
  displayName: "Build and push the web image"
  inputs:
    containerRegistry: 'acrpush'
    repository: 'web'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfile)'
    tags: '$(tag)'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
