apiVersion: apps/v1
kind: Deployment
metadata:
  name: __ACR.Name__
  namespace: __AKS.Namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __ACR.Name__
  template:
    metadata:
      labels:
        app: __ACR.Name__
    spec:
      containers:
      - name: __ACR.Name__
        image: __ACR.ImageName__
        ports:
        - containerPort: __Container.Port__
---
apiVersion: v1
kind: Service
metadata:
  name: __ACR.Name__
  namespace: __AKS.Namespace__
spec:
  selector:
    app: __ACR.Name__
  type: LoadBalancer
  ports:
  - port: __Container.Port__
