apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ""
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: ""
          image: ""
          ports:
          - containerPort: 0             
          envFrom:
          - configMapRef: deployConfigMap
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: leaderboard
spec:
  type: LoadBalancer
  ports:
  - port: 0
  selector:
    app: ""          
  envFrom:
  - configMapRef: deployConfigMap
